name: Marlin test, build, and publish

on:
  # Run on push to any branch, if .h files changed
  push:
    paths:
      - '*/*.h'
  # Run when manually triggered
  workflow_dispatch:

jobs:
  test-build-publish:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the configuration code at /myconfig
      - uses: actions/checkout@v2
        with:
          path: ./myconfig
      # Checkout the Marlin firmware code at /marlin
      - uses: actions/checkout@v2
        with:
          repository: MarlinFirmware/Marlin
          ref: 2.0.x
          path: ./marlin
      # Set up Python, to run PlatformIO
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      # Install and update PlatformIO
      - run: |
          pip install --upgrade platformio
          pio platform update
      # Copy config files into Marlin directory
      - run: |
          cp ./myconfig/CrealityV427/*.h ./marlin/Marlin/
      # Run Marlin tests
      - if: ${{ success() && ( github.ref != 'refs/heads/main' || github.event_name == 'workflow_dispatch' ) }}
        run: |
          make tests-single-local TEST_TARGET=STM32F103RET6_creality
        working-directory: ./marlin
      # Build Marlin firmware
      - if: ${{ success() && ( github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' ) }}
        run: |
          pio run -e STM32F103RET6_creality
        working-directory: ./marlin
