name: Build Marlin firmware

on:
  # Run on push to any branch, if .h files changed in main
  push:
    paths:
      - '*/*.h'
    branches:
      - main
  # Run when manually triggered
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      # Checkout the configuration code at /myconfig
      - uses: actions/checkout@v2
        with:
          path: ./myconfig
      # Checkout the Marlin firmware code at /marlin
      - uses: actions/checkout@v2
        with:
          repository: MarlinFirmware/Marlin
          ref: 2.0.x
          path: ./marlin
      # Install and update PlatformIO
      - run: |
          pip install --upgrade platformio
          pio platform update
      # Copy config files into Marlin directory
      - run: |
          cp ./myconfig/CrealityV427/*.h ./marlin/Marlin/
      # Build Marlin firmware
      - run: |
          pio run -e STM32F103RET6_creality
        working-directory: ./marlin
